# Generated by Django 4.2.1 on 2023-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_hired_alter_user_shift_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift_time',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
