# Generated by Django 4.2.1 on 2023-05-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='added_by',
        ),
    ]
